booking/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookings.urls', namespace='bookings')),
    path('users/', include('users.urls', namespace='users')),
]

bookings/urls.py
"Defines URL patterns for bookings."

from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
	path('', views.home, name='home'),
	path('<book_date>/delete', views.delete_book, name='delete-book'),
	path('date', views.date, name='date'),
	path('hours/<book_date>', views.hours, name='hours'),
	]

users/urls.py
"Define URL patterns for users."

from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'
urlpatterns = [
	path('login', LoginView.as_view(template_name='users/login.html'),
		name='login'),
	path('logout', views.logout_view, name='logout'),
	path('register', views.register, name='register'),
]

bookings/models.py
from django.db import models
from users.models import CustomUser

# Create your models here.
class Day(models.Model):
	"""This model contains the chosen date for the booking."""

	owner = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
	# hours reserved for a day
	reserved = models.PositiveIntegerField(default=0)
	date = models.DateField()

	def __str__(self):
		return str(self.date)

class Hours(models.Model):
	"""The hours for a specific day."""
	
	related_day = models.ForeignKey(Day,on_delete=models.CASCADE)
	h1 = models.BooleanField(default=False,blank=True,choices=((True,'Reserved'),(False,'Unreserved')))
	h2 = models.BooleanField(default=False,blank=True,choices=((True,'Reserved'),(False,'Unreserved')))
	h3 = models.BooleanField(default=False,blank=True,choices=((True,'Reserved'),(False,'Unreserved')))
	h4 = models.BooleanField(default=False,blank=True,choices=((True,'Reserved'),(False,'Unreserved')))
	h5 = models.BooleanField(default=False,blank=True,choices=((True,'Reserved'),(False,'Unreserved')))
	h6 = models.BooleanField(default=False,blank=True,choices=((True,'Reserved'),(False,'Unreserved')))
	h7 = models.BooleanField(default=False,blank=True,choices=((True,'Reserved'),(False,'Unreserved')))
	h8 = models.BooleanField(default=False,blank=True,choices=((True,'Reserved'),(False,'Unreserved')))
	h9 = models.BooleanField(default=False,blank=True,choices=((True,'Reserved'),(False,'Unreserved')))

	def __str__(self):
		return str(self.related_day)

bookings/forms.py
from django import forms
from django.core.exceptions import ValidationError
import datetime

from .models import Day, Hours

class DayForm(forms.ModelForm):
	class Meta:
		model = Day
		fields = ['date']
		#labels = {'firstname':'','lastname':'','datetime':''}
		widgets = {'date':forms.SelectDateWidget()}

	def clean_date(self):
		data = self.cleaned_data['date']

		# check if data is not in the past.
		if data < datetime.date.today():
			raise ValidationError('Invalid date - date is in past')
		elif data > datetime.date.today() + datetime.timedelta(weeks=2):
			raise ValidationError('Invalid date - can\'t book more than 2 weeks beforehand')

		return data

class HoursForm(forms.ModelForm):
	class Meta:
		model = Hours
		fields = ['h1','h2','h3','h4','h5','h6','h7','h8','h9']
		labels = {'h1':'09:00 to 10:00',
				'h2':'10:00 to 11:00',
				'h3':'11:00 to 12:00',
				'h4':'12:00 to 13:00',
				'h5':'13:00 to 14:00',
				'h6':'14:00 to 15:00',
				'h7':'15:00 to 16:00',
				'h8':'16:00 to 17:00',
				'h9':'17:00 to 18:00'}

bookings/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import datetime

from .forms import DayForm, HoursForm
from .models import Day, Hours
# Create your views here.

def home(request):
	"""Show the bookings a user has made if a user is authenticated."""
	if request.user.is_authenticated:
		days = Day.objects.filter(owner=request.user)
		context = {'days':days}
		return render(request,"bookings/home.html", context)
	else:
		return render(request,"bookings/home.html")

@login_required
def delete_book(request, book_date):
	"""Delete a booking."""
	# the object (one object)
	booking = Day.objects.filter(date=book_date, owner=request.user)
	if request.method == 'POST':
		#confirming delete.
		booking.delete()
		return HttpResponseRedirect(reverse('bookings:home'))

def match_objects_day(book_date, user):
	"""Select the corresponding object 'Day' for a user.
	return the object if it already existed, or False instead."""
	try:
		day = Day.objects.filter(date=book_date, owner=user)[0]
	except:
		return False
	else:
		return day

@login_required
def date(request):
	if request.method != 'POST':
		form = DayForm()
	else:
		# POST request, process..
		form = DayForm(request.POST)
		if form.is_valid():
			# check if the user had created an object for this date.
			book_date = datetime.date(int(request.POST['date_year']),int(request.POST['date_month']),
				int(request.POST['date_day']))

			if match_objects_day(book_date, request.user):
				#day = match_objects_day(book_date, request.user)
				messages.add_message(request, messages.ERROR,'You already have a booking for this day!')
				return HttpResponseRedirect(reverse("bookings:date"))

			else:
				day = form.save(commit=False)
				day.owner = request.user
				day.reserved = 0
				day.save()

			return HttpResponseRedirect(reverse('bookings:hours', args=[day.date]))

	context = {'form':form}
	return render(request, 'bookings/date.html', context)


@login_required
def hours(request,book_date):

	if request.method != 'POST':
		# 1-get the bookings for the day the user choose.		
		# 2-get the hours set objects, True value of a Hours model field means reserved.
		# 3-disable the already reserved hours.
		form = HoursForm()
		# check if there's room 
		day_set = Day.objects.filter(date=book_date)
		# max 25 bookings for each hour
		room = [2 for _ in range(9)]
		full = 9
		for d in day_set:
			#just one hours object but it's a query so iterate is necessary
			for h in d.hours_set.all():
				if h.h1:
					room[0] -= 1
					if not room[0]:
						full -= 1
						form.fields['h1'].widget.attrs['disabled'] = True
						form.fields['h1'].initial = True
				if h.h2:
					room[1] -= 1
					if not room[1]:
						full -= 1
						form.fields['h2'].widget.attrs['disabled'] = True
						form.fields['h2'].initial = True
				if h.h3:
					room[2] -= 1
					if not room[2]:
						full -= 1
						form.fields['h3'].widget.attrs['disabled'] = True
						form.fields['h3'].initial = True
				if h.h4:
					room[3] -= 1
					if not room[3]:
						full -= 1
						form.fields['h4'].widget.attrs['disabled'] = True
						form.fields['h4'].initial = True
				if h.h5:
					room[4] -= 1
					if not room[4]:
						full -= 1
						form.fields['h5'].widget.attrs['disabled'] = True
						form.fields['h5'].initial = True
				if h.h6:
					room[5] -= 1
					if not room[5]:
						full -= 1
						form.fields['h6'].widget.attrs['disabled'] = True
						form.fields['h6'].initial = True
				if h.h7:
					room[6] -= 1
					if not room[6]:
						full -= 1
						#no room left for this hour: disable
						form.fields['h7'].widget.attrs['disabled'] = True
						form.fields['h7'].initial = True
				if h.h8:
					room[7] -= 1
					if not room[7]:
						full -= 1
						form.fields['h8'].widget.attrs['disabled'] = True
						form.fields['h8'].initial = True
				if h.h9:
					room[8] -= 1
					if not room[8]:
						full -= 1
						form.fields['h9'].widget.attrs['disabled'] = True
						form.fields['h9'].initial = True
				# all hours are reserved fully, display error
				if full == 0:
					messages.add_message(request, messages.INFO,'No left room for this date - Please choose another date.')
					# delete the Day object that was created
					booking = Day.objects.get(date=book_date,owner=request.user)
					booking.delete()
					return HttpResponseRedirect(reverse("bookings:date"))

	else:
		form = HoursForm(request.POST)
		day = Day.objects.get(date=book_date,owner=request.user)
		if form.is_valid():
			# First time to book for this day.
			# build the relationship Hours-Day models.
			hours = form.save(commit=False)
			# the number of hours reserved for a day.
			hs = ['h1','h2','h3','h4','h5','h6','h7','h8','h9']
			for h in hs:
				if request.POST.get(h,False)=="True":
					day.reserved += 1
			day.save()

			hours.related_day = day
			hours.save()


			return HttpResponseRedirect(reverse('bookings:home'))

	context = {'form':form, 'date':book_date}
	return render(request,"bookings/hours.html", context)

bookings/templates/bookings/base.html
{% load bootstrap4 %}

<!DOCTYPE html>

<html lang='en' class="h-100">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  	<!-- Bootstrap CSS -->
  	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
  	<!-- load css and javascrips -->
  	{% bootstrap_css %}
  	{% bootstrap_javascript jquery='full'%}

  	<!--display django.contrib.messages as Bootstrap alerts
  	{% bootstrap_messages %}-->

		<title>My Bookings 2.0</title>
	</head>

	<body class="d-flex flex-column h-100">

		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="navbar-header">
				<a class="navbar-brand" href="#">Bookings</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
			</div>

			<div class="navbar-collapse collapse" id="navbarNav">
				<ul class="navbar-nav mr-auto  mx-4">
					{% if user.is_authenticated %}
						<li class="nav-item px-2">
							<a href="{% url 'bookings:home' %}">Home</a>
						</li>						
						<li class="nav-item">
							<a href="{% url 'bookings:date' %}">Reservation</a>
						</li>
				</ul>
				<ul class="navbar-nav">
						<li class="nav-item"><span class="navbar-text">Hello {{user.username}}</span></li>
						<li class="nav-item my-auto px-2">
							<a href="{% url 'users:logout' %}">Log out</a>
						</li>
					{% else %}
						<li class='nav-item mx-1'>
							<a href="{% url 'users:login' %}">Log in</a>
						</li>
						<li class='nav-item mx-1'>
							<a href="{% url 'users:register' %}">Sign up</a>
						</li>
					{% endif %}
				</ul>

			</div>
		</nav>





		<div class="container">

			<div class="pb-2 mt-4 mb-2 border-bottom">
				{% block header %}{% endblock header %}
			</div>
			<div class="mt-4">
				{% block content %}{% endblock content %}
			</div>
		</div>
			<footer class="footer mt-auto py-4 bg-dark text-white-50">
				<div class="container text-center text-muted">
					<small>Copyrights reserved Achahoud Inc.</small>
				</div>
			</footer>
		<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	</body>
</html>

bookings/templates/bookings/date.html
{% extends "bookings/base.html" %}
{% load bootstrap4 %}

{% block content %}

<h2>Book Now.</h2>
	<form class="form" method='post' action="{% url 'bookings:date' %}">
		{% csrf_token %}
		{% bootstrap_messages %}
		{% bootstrap_form form %}
		{% buttons %}
			<button name='submit' class="btn btn-success">Submit</button>
		{% endbuttons %}
	</form>

{% endblock content %}

bookings/templates/bookings/home.html
{% extends "bookings/base.html" %}
{% block header %}
<div class="jumbotron">
	<h1 class="display-4">Marhba to your bookings.</h1>
</div>
{% endblock header %}

{% block content %}

	{% if user.is_authenticated %}

		{% for day in days %}
		<h4>Reservations:</h4>
			<div class="card m-3">
				<h5 class="card-header">{{ day.date }}</h5>

					<div class="card-body">
						<span>You have reserved {{day.reserved}} hours.</span>
						<form action="{% url 'bookings:delete-book' day.date %}" method='POST'>
							{% csrf_token %}
							<input class="btn btn-outline-danger btn-sm mt-1" type='submit' value='Delete'/>
						</form>
					</div>

			</div>

		{% empty %}
			<text>No bookings have been made yet.</text>
		{% endfor %}
	

	{% else %}
		<h2>
			<a href="{% url 'users:register' %}">Register</a> now to make reservations.
			Or <a href="{% url 'users:login' %}">Log in</a> to your account.
		</h2>
	{% endif %}

{% endblock content %}

bookings/templates/bookings/hours.html
{% extends "bookings/base.html" %}
{% load bootstrap4 %}

{% block content %}

<h2>Select the hours to book.</h2>
<div class="mb-5">
	<form class="form" method='post' action="{% url 'bookings:hours' date %}">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button class="btn btn-success" name='submit'>Submit</button> -
			
			<a href="{% url 'bookings:home' %}" role='button'>
				<button type="button" class="btn btn-secondary">Cancel</button></a>
		{% endbuttons %}
	</form>
</div>
{% endblock content %}

bookings/templates/bookings/reservations.html
{% extends "bookings/base.html" %}

{% block content %}

<h2>Your bookings.</h2>
<ul>
	{% for day in days %}
	<li>

		<h3>{{ day.date }}</h3>
		
	</li>
	{% empty %}
		<li>No bookings have been made yet.</li>
	{% endfor %}
</ul>

{% endblock content %}